
[package]
name = "cc-unzip-media"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.6"
rar = "0.2.0"
ssh2 = "0.9.4"
rpassword = "7.3.1"